config/routes.rb
Bucketlist::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  match '/signout' => 'authentications#signout', :as => :signout
  match '/styles' => 'welcome#styles'
  resources :experiences do
    member do
      post 'vote'
    end
    resources :reviews
  end
  root :to => 'welcome#index'
end

app/models/experience.rb
class Experience
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  include Mongo::Voteable

  # set points for each vote
  voteable self, :up => +1, :down => -1

  has_mongoid_attached_file :image,
                            :storage        => :s3,
                            :s3_credentials => {access_key_id: ENV['S3_ACCESS_KEY_ID'], secret_access_key: ENV['S3_SECRET_ACCESS_KEY']},
                            :bucket         => 'uploads-bucketlist'
  field :title, type: String
  field :url, type: String
  field :description, type: String

  embeds_many :reviews
  belongs_to :user
end

app/models/review.rb
class Review
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongo::Voteable

  embedded_in :experience
  voteable self, :up => +1, :down => -1
  voteable Experience, :up => +2, :down => -1

  belongs_to :user
  field :text, type: String
  has_mongoid_attached_file :image,
                            :storage        => :s3,
                            :s3_credentials => {access_key_id: ENV['S3_ACCESS_KEY_ID'], secret_access_key: ENV['S3_SECRET_ACCESS_KEY']},
                            :bucket         => 'uploads-bucketlist'
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongo::Voter

  field :provider, type: String
  field :uid, type: String
  field :info, type: Hash

  def name
    self.info['name']
  end

  def picture_url
    self.info['image']
  end

  def self.find_or_create_by_provider_and_uid(auth)
    user = User.where(:provider => auth['provider'], :uid => auth['uid']).first
    user ||= User.create(auth.slice('provider', 'uid', 'info'))
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :signed_in?, :current_user, :admin?, :can_edit?

  def sign_in(user)
    session['user_id'] = user.id
  end

  def signed_in?
    session['user_id'].present?
  end

  def current_user
    nil unless signed_in?
    User.find(session['user_id'])
  end

  def admin?
    signed_in? && current_user.provider == "twitter" && (current_user.uid == "46238620" || current_user.uid == "14999406")
  end

  def can_edit?(object)
    return false unless signed_in?
    return true if admin?
    object.user == current_user
  end

end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    logger.info "OmniAuth#{auth}"
    user = User.find_or_create_by_provider_and_uid(auth)
    sign_in(user)
    redirect_to root_path, :notice => "Authentication successful."
  end

  def signout
    reset_session
    # redirect back here
    redirect_to request.referer || root_path, :notice => "Signed out!"
  end

  def destroy
    #@authentication = current_user.authentications.find(params[:id])
    #@authentication.destroy
    #flash[:notice] = "Successfully destroyed authentication."
    #redirect_to authentications_url
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  def index
    @experiences = Experience.all.order_by('votes.point'=>:desc)
  end

  def new
    @experience = Experience.new
  end

  def create
    if Experience.create(params[:experience].merge(:user=>current_user))
      redirect_to root_path, :notice => "Experience created"
    else
      render :new
    end
  end

  def edit
    @experience = Experience.find(params[:id])
  end

  def update
    @experience = Experience.find(params[:id])
    if @experience.update_attributes(params[:experience])
      redirect_to root_path, :notice => "Experience updated"
    else
      render :edit
    end
  end

  def destroy

  end

  def vote
    @experience = Experience.find(params[:id])
    @experience.reviews.create(params[:review].merge(:user=>current_user))
    current_user.vote(@experience, params[:vote].to_sym)
    redirect_to root_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @experience = Experience.find(params[:experience_id])
    if @experience.reviews.create(params[:review].merge(:user=>current_user))
      redirect_to root_path, :notice => 'Review created successfully'
    else
      redirect_to root_path, :alert => 'Failed to create a review'
    end
  end

  def update
    @experience = Experience.find(params[:experience_id])
    @review = @experience.reviews.find(params[:id])
    if @review.update_attributes(params[:review])
      redirect_to root_path, :notice => 'Review updated successfully'
    else
      redirect_to root_path, :alert => 'Failed to update review'
    end
  end

  def edit
    @experience = Experience.find(params[:experience_id])
    @review = @experience.reviews.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @experiences = Experience.all.order_by('votes.point'=>:desc)
  end

  def styles

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_experience.html.erb
<div class="row-fluid borBox well deep experience" style="position:relative;">
  <div class="span1 vote">
    <%= render :partial => 'experiences/inline_vote_form', :locals => {:experience => experience, :vote => :up} %>
    <div><span class="count"><%= experience.votes_point %></span></div>
    <%= render :partial => 'experiences/inline_vote_form', :locals => {:experience => experience, :vote => :down} %>
  </div>
  <div class="span4">
    <ul class="thumbnails">
      <li class="span4">
        <a href='<%= experience.url %>' class="thumbnail" target='_blank'>
          <%= image_tag experience.image %>
        </a>

        <div style="text-align: center; margin-top: 10px;">
        <span style="">
          <span class='st_facebook_large' displayText='Facebook'></span>
          <span class='st_twitter_large' displayText='Tweet'></span>
          <span class='st_email_large' displayText='Email'></span>
          <span class='st_sharethis_large' displayText='ShareThis'></span>

          <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
          <script type="text/javascript">stLight.options({publisher:"2a8bfbf8-e506-4c99-bd55-c67e8461c2e0"}); </script>
        </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="span7">
    <div class="">
      <%= link_to experience.url, :class => 'inverse', :style => '', :target => '_blank' do %>
        <h1><%= experience.title %></h1>
      <% end %>
    </div>
    <div>
      <%= raw experience.description %>
    </div>
    <div class="reviews borBox well trans">
      <%= render experience.reviews %>
    </div>
  </div>
  <% if can_edit?(experience) %>
    <%= link_to "Edit", edit_experience_path(experience), :class => ['btn', 'edit'], :style => "position:absolute; top: 12px; right:10px;" %>
  <% end %>
</div>

<% content_for :javascripts do %>
  <script type="text/javascript">
    $(function () {
      $('a.edit').hide();
      $('.experience').hover(function () {
        $(this).children('a.edit').show();
      }, function () {
        $(this).children('a.edit').hide();
      });
    });
  </script>
<% end %>

app/views/experiences/_form.html.erb
<%= simple_form_for(@experience, :html => {:class => 'form-horizontal'}) do |form| %>
  <%= form.error_notification %>
  <div class="form-inputs">
    <%= form.input :image %>
    <%= form.input :title, :input_html => { :class => 'span8' } %>
    <%= form.input :url, :input_html => { :class => 'span8' } %>
    <%= form.input :description, :as => :text, :input_html => { :class => 'span8' } %>
  </div>
  <div class='form-actions'>
    <%= form.button :submit, :class => 'btn-primary' %>
    <%= link_to "Back", root_path, :class=>"btn" %>
  </div>
<% end %>

<script type="text/javascript">
    $('textarea').wysihtml5();
</script>

app/views/experiences/_inline_vote_form.html.erb
<%= link_to signed_in? ? "#experience_#{experience.id}_#{vote}" : "#signin", :data => {:toggle => 'modal'} do %>
  <div class="<%= vote.to_s %>vote">
  </div>
<% end %>

<% content_for :modals do %>
  <div class="modal span8" id="experience_<%= experience.id %>_<%= vote %>">
    <div class="modal-header">
      <span class="close" data-dismiss="modal">×</span>
      <h3>
        <%= experience.title %>
        <small><%= vote.to_s.titleize + 'vote' %></small>
      </h3>
    </div>
    <%= simple_form_for([experience, Review.new], :url => vote_experience_path(experience, :vote=>vote), :html => {:class => '.form-vertical'}) do |form| %>
      <div class="modal-body">
        <%= form.input :text, :label=>false, :as=>:text, :input_html => { :id=>"experience_#{experience.id}_#{vote}_text", :style => 'width:100%' } %>
        <%= form.input :image, :label=>false, :input_html => { :style => 'width:100%' } %>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
        <%= form.button :submit, :class => 'btn-inverse' %>
      </div>
    <% end %>
  </div>
<% end %>

<% content_for :javascripts do %>
  <script type="text/javascript">
    $(function(){
      $('#experience_<%= experience.id %>_<%= vote %>').modal().modal('hide');
      $('#experience_<%= experience.id %>_<%= vote %>_text').wysihtml5();
    })
  </script>
<% end %>

app/views/experiences/edit.html.erb
<h2 style="padding-left: 160px;">Edit Your Experience</h2>
<%= render :partial => 'form' %>

app/views/experiences/index.html.erb
<h1>Experiences</h1>
<%= render @experiences %>

app/views/experiences/new.html.erb
<h2 style="padding-left: 160px;">Submit Your Experience</h2>
<%= render :partial => 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bucketlist</title>
  <meta charset='utf-8'>
  <%= stylesheet_link_tag "application", :debug => Rails.env.development? %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield :modals %>

<div class="fronty">
  <!-- THE TOP NAVBAR -->
  <div id="topLink"></div>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid" style="min-height:40px;">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <div class="nav-collapse">
          <div class="pull-right">
            <% if signed_in? %>
              <%= image_tag current_user.picture_url %>
              <%= current_user.name %>
            <% else %>
              <a class="btn btn-info btn-small round2" data-toggle="modal" href="#signin">
                <i class="icon-white icon-user"></i> Sign In
              </a>
            <% end %>
          </div>
          <ul class="nav pull-right">
            <% if signed_in? %>
              <li> <%= link_to 'Submit Your Experience', new_experience_path, :class => "smooth" %> </li>
              <li> <%= link_to 'Signout', signout_path, :class => "smooth" %> </li>
            <% end %>
          </ul>
        </div>

      </div>
    </div>
  </div>
  <!-- SOCIAL MEDIA -->

  <!-- CONTAINER STARTS -->
  <div class="container-fluid pad58">
    <br/><br/>

    <div class="row-fluid">
      <div class="mainlogo">
        <%= image_tag "Bucket_List_4.png", :style => "margin-left: -240px;" %>
      </div>
    </div>

    <%= yield %>

  </div>

</div>

<div class="bgbox">
</div>

<div class="modal hide fade" id="signin">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>

    <h3>Sign in Details</h3>
  </div>
  <div class="modal-body">
    <h2>Sign in with:</h2>
    <div>
      <%= link_to '/auth/twitter', :class=>['btn', 'btn-large' ] do%>
        <%= image_tag 'authbuttons/twitter_32.png' %>
        <span style="font-weight: bold;">Twitter</span>
      <% end %>
      <%= link_to '/auth/facebook', :class=>['btn', 'btn-large' ] do%>
        <%= image_tag 'authbuttons/facebook_32.png' %>
        <span style="font-weight: bold;">Facebook</span>
      <% end %>
    </div>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>


<%= yield :javascripts %>

</body>
</html>

app/views/reviews/_inline_new_review.html.erb
<%= link_to "Review", "#experience_#{experience.id}", :class => ['btn', 'btn-inverse'], :data => {:toggle => 'modal'} %>

<% content_for :modals do %>
  <div class="modal span8" id="experience_<%= experience.id %>">
    <div class="modal-header">
      <span class="close" data-dismiss="modal">×</span>
      <h3>
        <%= experience.title %>
        <small>Review</small>
      </h3>
    </div>
    <%= simple_form_for([experience, Review.new], :html => {:class => '.form-vertical'}) do |form| %>
      <div class="modal-body">
        <%= form.input :title, :label=>false, :placeholder=>'Title', :input_html => { :style => 'width:100%' } %>
        <%= form.input :text, :label=>false, :as=>:text, :input_html => { :style => 'width:100%' } %>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
        <%= form.button :submit, :class => 'btn-inverse' %>
      </div>
    <% end %>
  </div>
<% end %>

<% content_for :javascripts do %>
  <script type="text/javascript">
    $(function(){
      $('#experience_<%= experience.id %>').modal().modal('hide');
      //$('textarea').wysihtml5();
    })
  </script>
<% end %>

app/views/reviews/_review.html.erb
<div data-toggle="collapse" data-target="#<%= review.id %>" style="position:relative;">
  <div style="cursor:pointer;">
    <h3>
      <%= image_tag review.user.picture_url, :size => '40x40' %>
      <%= review.user.name %>
    </h3>
  </div>
  <div id="<%= review.id %>" class="collapse">
    <div>
      <%= raw review.text %>
    </div>
    <% if review.image.present? %>
      <div class="row">
        <div class="span4 offset1">
          <ul class="thumbnails">
            <li class="span4">
              <%= image_tag review.image, :class => "thumbnail span4" %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
  <% if can_edit?(review) %>
    <%= link_to "Edit review", edit_experience_review_path(review.experience, review), :style => "position:absolute; top: 10px; right:10px;" %>
  <% end %>
  <hr/>
</div>

app/views/reviews/edit.html.erb
<%= simple_form_for([@experience, @review], :html => {:class => '.form-vertical'}) do |form| %>
  <div class="modal-body">
    <%= form.input :text, :label=>false, :as=>:text, :input_html => { :id=>"experience_#{@experience.id}_text", :style => 'height:10em;width:100%' } %>
    <%= form.input :image, :label=>false, :input_html => { :style => 'width:100%' } %>
  </div>
  <div class="form-actions">
    <%= form.button :submit, :class => 'btn-inverse' %>
  </div>
<% end %>

<% content_for :javascripts do %>
  <script type="text/javascript">
    $(function(){
      $('#experience_<%= @experience.id %>_text').wysihtml5();
    })
  </script>
<% end %>

app/views/welcome/_carousel.html.erb
<!-- CAROUSEL BOX START -->
<div class="row-fluid borBox inBox well deep">
  <div class="page-header inverse">
    <h1>Bucketlist
      <small> make some day today</small>
    </h1>
  </div>
  <div id="myCarousel" class="carousel">
    <!-- Carousel items -->
    <div class="carousel-inner">
      <div class="active item">
        <div class="bgimg1">
          <br/>
        </div>
      </div>
      <div class="item">
        <div class="bgimg2">
          <br/>
        </div>
      </div>
      <div class="item">
        <div class="bgimg3">
          <br/>
        </div>
      </div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
  </div>
</div>
<!-- CAROUSEL BOX END -->

app/views/welcome/_categories.html.erb
<!-- CATEGORIES BOX START -->

<div class="row-fluid" id="showcase">
  <div class="span3">
    <div class="borBox well deep">
      <div class="page-header inverse">
        <h1>HTML5
          <small> great use of proper semantics</small>
        </h1>
      </div>
      <div class="feature1"><br/></div>
    </div>
  </div>
  <div class="span3">
    <div class="borBox well deep">
      <div class="page-header inverse">
        <h1>CSS3
          <small> adding aestheics and professionalism</small>
        </h1>
      </div>
      <div class="feature2"><br/></div>
    </div>
  </div>
  <div class="span3">
    <div class="borBox well deep">
      <div class="page-header inverse">
        <h1>jQuery
          <small> dynamism to your work</small>
        </h1>
      </div>
      <div class="feature3"><br/></div>
    </div>
  </div>
  <div class="span3">
    <div class="borBox well deep">
      <div class="page-header inverse">
        <h1>Clean Design
          <small> To Love Me</small>
        </h1>
      </div>
      <div class="feature4"><br/></div>
    </div>
  </div>

</div>
<!-- CATEGORIES BOX END -->

app/views/welcome/_features.html.erb
<div class="row-fluid borBox well deep" id="features">
  <div class="page-header inverse">
    <h1>Features
      <small> the work i put in</small>
    </h1>
  </div>
  <div class="row-fluid">
    <div class="span4 borBox">
      <ul class="bigWhiteList">
        <li>CSS3 Transitions</li>
        <li>HTML5</li>
        <li>Responsive and Fluid Layout</li>
        <li>Tested on iPad, iPhone, Android and Desktops and Laptops</li>
        <li>Works Everywhere</li>
        <li>Single Page to Showcase Your Stuff</li>
        <li>Intelligent and Smart Code</li>
      </ul>
    </div>
    <div class="span4 borBox">
      <ul class="bigWhiteList">
        <li>Rock-Solid Reliability</li>
        <li>New Buttons</li>
        <li>New Elements, Extend Bootstrap</li>
        <li>Transparent Navbar, You know you wanted it so bad! :)</li>
        <li>Noise Background</li>
        <li>Immensely Extensible</li>
      </ul>
    </div>
    <div class="span4 borBox">
      <ul class="bigWhiteList">
        <li>Impress Your Clients</li>
        <li>Showcase Your Work</li>
        <li>Make It Elegant</li>
        <li>Use Elegancy!</li>
      </ul>
    </div>
  </div>
</div>

app/views/welcome/_follow_links.html.erb
<ul class="social unstyled follow">
  <li class="fb"><a href="#" rel="tooltip">Facebook</a></li>
  <li class="tumblr"><a href="#" rel="tooltip">Tumblr</a></li>
  <li class="pinterest"><a href="#" rel="tooltip">Pinterest</a></li>
  <li class="twitter"><a href="#" rel="tooltip">Twitter</a></li>
</ul>

app/views/welcome/_main_logo_middle.html.erb
<div class="row-fluid">
  <div class="mainlogo">
    <%= link_to root_path do %>
      <%= image_tag "mainlogo.png" %>
    <% end %>
  </div>
</div>
<br/>

app/views/welcome/_social_links.html.erb
<div class="row-fluid borBox inBox well deep">
  <ul class="social unstyled links">
    <li class="fb"><a href="#" rel="tooltip">Facebook</a></li>
    <li class="twitter"><a href="#" rel="tooltip">Twitter</a></li>
    <li class="rss"><a href="#" rel="tooltip">RSS</a></li>
    <li class="gplus"><a href="#" rel="tooltip">Google+</a></li>
    <li class="blog"><a href="#" rel="tooltip">Blog</a></li>
    <li class="flickr"><a href="#" rel="tooltip">Flickr</a></li>
  </ul>
</div>

app/views/welcome/index.html.erb
<%= render @experiences %>
<%= render :partial => 'social_links' %>
<div class="row-fluid borBox well deep" id="contactFooter">
  <%= render :partial => 'follow_links' %>
</div>

app/views/welcome/styles.html.erb
<%= render :partial => 'carousel' %>

<!-- INTRO BOX -->
<%= render :partial => 'social_links' %>
<%= render :partial => 'follow_links' %>
<!-- INTRO BOX END -->

<%= render :partial => 'categories' %>
<%= render :partial => 'features' %>
<div class="row-fluid borBox well deep" id="newElements">
  <div class="page-header inverse">
    <h1>New Styles
      <small> Many New Styles Ready To Use</small>
    </h1>
  </div>
  <br/>

  <div class="row-fluid">
    <div class="span6 borBox">
      <div class="borBox well">
        <hr/>
        <br/>Simple Well<br/><br/>
        <hr/>
      </div>
    </div>
    <div class="span6 borBox">
      <div class="borBox well trans">
        <hr/>
        <br/>Transparent Well<br/><br/>
        <hr/>
      </div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span6 borBox">
      <div class="borBox well light">
        <hr/>
        <br/>Light Well<br/><br/>
        <hr/>
      </div>
    </div>
    <div class="span6 borBox">
      <div class="borBox well deep">
        <hr/>
        <br/>Deep Well<br/><br/>
        <hr/>
      </div>
    </div>
  </div>
  <br/><br/>

  <div class="row-fluid">
    <div class="borBox">
      <h3 class='inverse'>New Navbar</h3><br/>

      <div class="navbar wid40">
        <div class="navbar-inner">
          <div class="container-fluid">
            <a class="brand">Semi-Transparent Navbar</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br/><br/>

  <div class="row-fluid buttonExample">
    <div class="span4 borBox">
      <div class="borBox well light">
        <div class="page-header inverse">
          <h1>Less Rounded Buttons</h1>
        </div>
        <button class="btn round2">Button</button>
        <button class="btn btn-primary round2">Button</button>
        <button class="btn btn-info round2">Button</button>
        <button class="btn btn-success round2">Button</button>
        <button class="btn btn-warning round2">Button</button>
        <button class="btn btn-danger round2">Button</button>
        <button class="btn btn-inverse round2">Button</button>
      </div>
    </div>
    <div class="span4 borBox">
      <div class="borBox well light">
        <div class="page-header inverse">
          <h1>Full Rounded Buttons</h1>
        </div>
        <button class="btn roundall">Button</button>
        <button class="btn btn-primary roundall">Button</button>
        <button class="btn btn-info roundall">Button</button>
        <button class="btn btn-success roundall">Button</button>
        <button class="btn btn-warning roundall">Button</button>
        <button class="btn btn-danger roundall">Button</button>
        <button class="btn btn-inverse roundall">Button</button>
      </div>
    </div>
    <div class="span4 borBox">
      <div class="borBox well light">
        <div class="page-header inverse">
          <h1>Sharp Buttons</h1>
        </div>
        <button class="btn roundnone">Button</button>
        <button class="btn btn-primary roundnone">Button</button>
        <button class="btn btn-info roundnone">Button</button>
        <button class="btn btn-success roundnone">Button</button>
        <button class="btn btn-warning roundnone">Button</button>
        <button class="btn btn-danger roundnone">Button</button>
        <button class="btn btn-inverse roundnone">Button</button>
      </div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="borBox well light">
      <div class="page-header inverse">
        <h1>New page-header Element
          <small> Just Add 'inverse' class to any page-header</small>
        </h1>
      </div>

      <h2 class='inverse'>Also, 'inverse' can be added to any text-element to convert it into this style</h2>
    </div>
  </div>
</div>
<div class="row-fluid borBox well deep">
  <div class="page-header inverse">
    <h1>Elements
      <small> A Demo of Awesomeness</small>
    </h1>
  </div>
  <div class="row-fluid">
    <div class="span4 borBox">
      <div class="borBox well light">
        <h2 class="inverse">ProgressBars</h2><br/>

        <div class="progress">
          <div class="bar" style="width: 40%;"></div>
        </div>
        <div class="progress progress-striped">
          <div class="bar" style="width: 60%;"></div>
        </div>
        <div class="progress progress-striped active">
          <div class="bar" style="width: 80%;"></div>
        </div>
      </div>
    </div>
    <div class="span4 borBox">
      <div class="borBox well light">
        <h2 class="inverse">Buttons</h2><br/>
        <button class="btn btn-primary">Primary</button>
        <button class="btn btn-info">Info</button>
        <button class="btn btn-success">Success</button>
        <button class="btn btn-inverse">Inverse</button>
      </div>
    </div>
    <div class="span4 borBox">
      <div class="borBox well light">
        <h2 class="inverse">Other Elements</h2><br/>
        <blockquote>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante venenatis.</p>
          <small>Someone famous</small>
        </blockquote>
      </div>
    </div>
  </div>

</div>

<div class="row-fluid borBox well deep" id="contactFooter">
  <div class="page-header inverse">
    <h1>Footer</h1>
  </div>
  <h2 class='inverse'>Add Contact Details Here</h2>
</div>